version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detail:
    format: '%(asctime)s - %(levelname)s - File: %(filename)s - %(funcName)s() - Line: %(lineno)d -  %(message)s'


root:
  level: DEBUG
  handlers: [console]
  # [console, all] to add file logging
  propagate: true

loggers:
  all:
    handlers: [console]
    # [console, all] to add file logging
    propagate: true

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
#  all:
#    class: logging.handlers.TimedRotatingFileHandler
#    level: DEBUG
#    formatter: simple
#    when: W0
#    backupCount: 4
#    filename: heatmiser.log # move to /var/log/heatmiser.log on linux
